# Generated by Django 4.2 on 2023-04-20 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transfer", "0004_alter_balance_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
