# Generated by Django 4.2 on 2023-04-22 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("transfer", "0006_sendfund"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendfund",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="sendfund",
            name="receiver",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="sendfund",
            name="sender",
            field=models.CharField(max_length=20),
        ),
    ]
