# Generated by Django 4.2 on 2023-04-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfer", "0007_sendfund_date_alter_sendfund_receiver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendfund",
            name="quote_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="sendfund",
            name="receiver_currency",
            field=models.CharField(default="GBP", max_length=3),
        ),
        migrations.AddField(
            model_name="sendfund",
            name="sender_currency",
            field=models.CharField(default="GBP", max_length=3),
        ),
    ]
