# Generated by Django 4.2 on 2023-04-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfer", "0009_requestfund"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestfund",
            name="approved",
            field=models.TextField(default="NO"),
        ),
    ]
